name: rank2-make-tune
channels:
  - conda-forgemamba env list
  - defaults
dependencies:
  - python=3.10
  - blas[build=mkl]
  - scipy
  - cvxpy=1.3.2
  - scikit-learn
  - pandas
  - google-auth
  - pandas-gbq>=0.19.2
  - dask
  - coiled
  - sqlalchemy
  - pg8000
  - cloud-sql-python-connector
  - pip
  - pip:
    - git+https://github.com/adonoho/EMS.git
    - google-cloud-bigquery
variables:
  MKL_NUM_THREADS: '1'
  OPENBLAS_NUM_THREADS: '1'
